dist: trusty
sudo: false
 
language: node_js
node_js:
  - 10
 
addons:
   chrome: stable
      
cache:
  directories:
    - ./node_modules

install:
  - npm ci
 
script:
  - npm run setup:install
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm run e2e
  
  
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js