language: node_js
sudo: false
node_js:
  - 10

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install
  
script:
  - npm run test -- --watch=false --browsers=ChromeHeadlessNoSandbox

after_success:
  - npm run coverage